### ISSUE TITLE
When I ran the tvm_pytorch_resnet18_inference.py, I met the problem

### ISSUE THREAD

**Issue by Jie-KUN** [BBuf/tvm_learn#2]
One or more operators have not been tuned. Please tune your model for better performance. Use DEBUG logging level to see more details.
Relay top-1 id: 281, class name: tabby, tabby cat, class probality: 0.3626886010169983
Torch top-1 id: 281, class name: tabby, tabby cat, class probality: 0.36268892884254456
Relay time(ms): 41.741
Torch time(ms): 16.326
free(): invalid pointer
Aborted

**Comment by ToleranceGui** [comment]
I met the same problem, how did you solve it?
thanks

**Comment by Jie-KUN** [comment]
/tvm/build/config.cmake
set(USE\_LLVM "/usr/bin/llvm-config --link-static")
set(USE\_MICRO OFF) 
/tvm/CMakelist.txt
set(HIDE\_PRIVATE\_SYMBOLS ON)\\
cmake -DCMAKE\_BUILD\_TYPE=Debug ../
make -j16
I modify the above .

**Comment by ToleranceGui** [comment]
these modifications worked
I have a new puzzle.
In terms of reasoning time, relay reasoning time  is longer, which does not reflect the optimization effect of TVM?

**Comment by GeneralJing** [comment]
> these modifications worked I have a new puzzle. In terms of reasoning time, relay reasoning time is longer, which does not reflect the optimization effect of TVM?

same question.
Relay time:  0.37134288150118666 seconds
Torch time:  0.0024548148998292164 seconds

**Comment by BBuf** [comment]
> these modifications worked I have a new puzzle. In terms of reasoning time, relay reasoning time is longer, which does not reflect the optimization effect of TVM?

You should use AutoTVM or Ansor to optimize it. Please refer to : https://tvm.apache.org/docs/tutorial/autotvm_relay_x86.html & https://tvm.apache.org/docs/tutorial/auto_scheduler_matmul_x86.html
