### ISSUE TITLE
关于PET论文阅读里面的一点疑问？

### ISSUE THREAD

**Issue by Wanger-SJTU** [BBuf/tvm_learn#4]
在介绍 部分等价变换的时候，shape变换是
> [b, c, h, w] -> reshape -> [b / 2, 2, c, h, w] -> transpose -> [b / 2, c , h, w, 2] 。

按照配图以及原文的内容

> It concatenates two individual images into a larger one along the width dimension to improve performance.

这里的shape变换是不是应该为
> [b, c, h, w] -> reshape -> [b / 2, 2, c, h, w] -> transpose -> [b / 2, c , h, w, 2] -> concat ->[b / 2, c , h, w*2]

**Comment by Wanger-SJTU** [comment]
按照我的理解，这里计算结果不等价的原因是因为，concat以后，再对输入做padding，这时候相对于concat前，是不等价。

**Comment by BBuf** [comment]
> 在介绍 部分等价变换的时候，shape变换是
> 
> > [b, c, h, w] -> reshape -> [b / 2, 2, c, h, w] -> transpose -> [b / 2, c , h, w, 2] 。
> 
> 按照配图以及原文的内容
> 
> > It concatenates two individual images into a larger one along the width dimension to improve performance.
> 
> 这里的shape变换是不是应该为
> 
> > [b, c, h, w] -> reshape -> [b / 2, 2, c, h, w] -> transpose -> [b / 2, c , h, w, 2] -> concat ->[b / 2, c , h, w*2]

是的，我那个表述需要refine一下。不过这里没有显示的concat，只有reshape+transpose，这个concat是不需要的，可以直接reshape成[b/2, c, h, w/2*2]

**Comment by BBuf** [comment]
> 按照我的理解，这里计算结果不等价的原因是因为，concat以后，再对输入做padding，这时候相对于concat前，是不等价。

这是一个原因，另外一个原因就是变换后的边界处可能有多余的计算导致数值错了。
